---
blank_issues_enabled: false
contact_links:
  - name: Swaplace Community Support
    url: https://github.com/blockful-io/swaplace-cairo/discussions
    about: Please ask and answer questions here.
